name: Java CI with Maven and ServeRest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install ServeRest
        run: npm install -g serverest@latest

      - name: Start ServeRest in background
        run: |
          serverest &
          sleep 5 # Wait for 5 seconds for ServeRest to start

      - name: Run Maven tests
        run: mvn test
