name: APICieloTransaçõesTestes

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: "mongodb+srv://gillvanjs:KNAqSlJj0n6mawLV@cluster0.yia8ilv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: KNAqSlJj0n6mawLV
      PORT: 3000

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # ou a versão que seu projeto utiliza

    - name: Install banco-api dependencies
      run: npm install
      working-directory: ./banco-api

    - name: Start banco-api server
      run: npm run rest-api &
      working-directory: ./banco-api
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        mvn -B clean
        mvn -B package --file pom.xml -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
    
    - name: Run Tests
      run: mvn test -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/
        retention-days: 30
